include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsRenderContext

libNPEngineGraphicsRenderContext_OBJC_FILES = \
NPOpenGLPixelFormat.m \
NPOpenGLRenderContext.m \
NPOpenGLRenderContextManager.m

libNPEngineGraphicsRenderContext_HEADER_FILES = \
NPOpenGLPixelFormat.h \
NPOpenGLRenderContext.h \
NPOpenGLRenderContextManager.h

libNPEngineGraphicsRenderContext_LIBRARIES_DEPEND_UPON += -lGLEW

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

