include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=OceanSpectra

OceanSpectra_OBJC_FILES = \
    main.m

OceanSpectra_C_FILES = \
    ODEnergy.c

OceanSpectra_HEADER_FILES = \
    ODEnergy.h

ADDITIONAL_TOOL_LIBS += -lNPEngine2 -lglfw

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/tool.make

