include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineImage
LIBRARY_NAME=libNPEngineImage

libNPEngineImage_HEADER_FILES = \
NPDevilTexture.h

libNPEngineImage_OBJC_FILES = \
NPDevilTexture.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
