include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsCamera

libNPEngineGraphicsCamera_HEADER_FILES = \
NPCamera.h \
NPCameraManager.h

libNPEngineGraphicsCamera_OBJC_FILES = \
NPCamera.m \
NPCameraManager.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

