include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=ODMenu

ODMenu_HEADER_FILES = \
ODMenu.h \
ODMenuItem.h \
ODButtonItem.h \
ODCheckboxItem.h \
ODSelectionGroupItem.h

ODMenu_OBJC_FILES = \
ODMenu.m \
ODMenuItem.m \
ODButtonItem.m \
ODCheckboxItem.m \
ODSelectionGroupItem.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

