include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineCoreTimer
LIBRARY_NAME=libNPEngineCoreTimer

libNPEngineCoreTimer_OBJC_FILES = \
NPTimer.m

libNPEngineCoreTimer_HEADER_FILES = \
NPTimer.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
