include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsEffect

libNPEngineGraphicsEffect_OBJC_FILES = \
NPShader.m

libNPEngineGraphicsEffect_HEADER_FILES = \
NPShader.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

