include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsEffect

libNPEngineGraphicsEffect_OBJC_FILES = \
NPShader.m \
NPEffect.m \
NPEffectTechnique.m \
NPEffectTechniqueVariable.m \
NPEffectVariable.m \
NPEffectVariableSampler.m \
NPEffectVariableSemantic.m \
NPEffectVariableUniform.m \
NPEffectVariableFloat.m \
NPEffectVariableInt.m \
NPEffectVariableBool.m

libNPEngineGraphicsEffect_HEADER_FILES = \
NPShader.h \
NPEffect.h \
NPEffectTechnique.h \
NPEffectTechniqueVariable.h \
NPEffectVariable.h \
NPEffectVariableSampler.h \
NPEffectVariableSemantic.h \
NPEffectVariableUniform.h \
NPEffectVariableFloat.h \
NPEffectVariableInt.h \
NPEffectVariableBool.h


include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

