include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsEffect

libNPEngineGraphicsEffect_OBJC_FILES = \
NPShader.m \
NPEffect.m \
NPEffectTechnique.m \
NPEffectTechniqueVariable.m

libNPEngineGraphicsEffect_HEADER_FILES = \
NPShader.h \
NPEffect.h \
NPEffectTechnique.h \
NPEffectTechniqueVariable.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

