include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=OceanDemo

OceanDemo_OBJC_FILES = \
main.m

ADDITIONAL_TOOL_LIBS += -lGL -lGLU -lNPEngine2 -lGLEW -lIL -lILU -lopenal -lvorbisfile -lglfw

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/tool.make

