include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineApplication

libNPEngineApplication_OBJC_FILES = \
NPApplication.m \
NPApplicationController.m \
NPWindowController.m \
NPOpenGLView.m

libNPEngineApplication_HEADER_FILES = \
NPApplication.h \
NPApplicationController.h \
NPWindowController.h \
NPOpenGLView.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

