include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsBuffer

libNPEngineGraphicsBuffer_HEADER_FILES = \
NPBufferObject.h \
NPCPUBuffer.h

libNPEngineGraphicsBuffer_OBJC_FILES = \
NPBufferObject.m \
NPCPUBuffer.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

