include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreWorld

libNPEngineCoreWorld_OBJC_FILES = \
NPTransformationState.m

libNPEngineCoreWorld_HEADER_FILES = \
NPTransformationState.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

