include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineCoreWorld
LIBRARY_NAME=libNPEngineCoreWorld

libNPEngineCoreWorld_OBJC_FILES = \
NPTransformationState.m \
NPTransformationStateManager.m

libNPEngineCoreWorld_HEADER_FILES = \
NPTransformationState.h \
NPTransformationStateManager.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
