include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineGraphicsCamera
LIBRARY_NAME=libNPEngineGraphicsCamera

libNPEngineGraphicsCamera_HEADER_FILES = \
NPCamera.h \
NPCameraManager.h

libNPEngineGraphicsCamera_OBJC_FILES = \
NPCamera.m \
NPCameraManager.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
