include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphics

libNPEngineGraphics_SUBPROJECTS = \
    Image \
    Texture \
    Effect \
    State

libNPEngineGraphics_C_FILES = \
NPEngineGraphicsEnums.c

libNPEngineGraphics_OBJC_FILES = \
NPEngineGraphics.m \
NPEngineGraphicsStringEnumConversion.m \
NSString+NPEngineGraphicsEnums.m

libNPEngineGraphics_HEADER_FILES = \
NPEngineGraphics.h \
NPEngineGraphicsEnums.h \
NPEngineGraphicsErrors.h \
NPEngineGraphicsStringEnumConversion.h \
NSString+NPEngineGraphicsEnums.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make



