include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsRenderTarget

libNPEngineGraphicsRenderTarget_HEADER_FILES = \
NPRenderBuffer.h \
NPRenderTexture.h \
NPRenderTargetConfiguration.h \
NPRenderTargetManager.h

libNPEngineGraphicsRenderTarget_OBJC_FILES = \
NPRenderBuffer.m \
NPRenderTexture.m \
NPRenderTargetConfiguration.m \
NPRenderTargetManager.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

