include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineSound

libNPEngineSound_HEADER_FILES = \
NPEngineSound.h \
NPSoundChannel.h \
NPSoundChannels.h \
NPSoundSample.h \
NPSoundManager.h \
NPSoundWorld.h \
NPSoundStream.h

libNPEngineSound_OBJC_FILES = \
NPEngineSound.m \
NPSoundChannel.m \
NPSoundChannels.m \
NPSoundSample.m \
NPSoundManager.m \
NPSoundWorld.m \
NPSoundStream.m

libNPEngineSound_LIBRARIES_DEPEND_UPON += -lopenal -lvorbis -lvorbisfile

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make



