include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineSound

libNPEngineSound_HEADER_FILES = \
NPEngineSound.h

libNPEngineSound_OBJC_FILES = \
NPEngineSound.m

libNPEngineSound_LIBRARIES_DEPEND_UPON += -lopenal -lvorbis -lvorbisfile

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make



