include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=ODEntities

ODEntities_HEADER_FILES = \
ODPEntity.h \
ODEntity.h \
ODCamera.h \
ODProjector.h \
ODFrustum.h

ODEntities_OBJC_FILES = \
ODEntity.m \
ODCamera.m \
ODProjector.m \
ODFrustum.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

