include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=ODEntities

ODEntities_SUBPROJECTS = \
    Ocean

ODEntities_HEADER_FILES = \
ODPEntity.h \
ODEntity.h \
ODCamera.h \
ODProjector.h \
ODFrustum.h \
ODOceanEntity.h \
ODProjectedGrid.h \
ODPerlinNoise.h \
ODPreethamSkylight.h

ODEntities_OBJC_FILES = \
ODEntity.m \
ODCamera.m \
ODProjector.m \
ODFrustum.m \
ODOceanEntity.m \
ODProjectedGrid.m \
ODPerlinNoise.m \
ODPreethamSkylight.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

