include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreString

libNPEngineCoreString_OBJC_FILES = \
NSString+NPEngine.m \
NPStringList.m \
NPParser.m

libNPEngineCoreString_HEADER_FILES = \
NSString+NPEngine.h \
NPStringList.h \
NPParser.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

