include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineGraphicsRenderTarget
LIBRARY_NAME=libNPEngineGraphicsRenderTarget

libNPEngineGraphicsRenderTarget_HEADER_FILES = \
NPRenderBuffer.h \
NPRenderTargetConfiguration.h

libNPEngineGraphicsRenderTarget_OBJC_FILES = \
NPRenderBuffer.m \
NPRenderTargetConfiguration.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
