include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=ODMenu

ODMenu_HEADER_FILES = \
ODSliderItem.h \
ODCheckBoxItem.h \
ODSelectionGroup.h \
ODMenu.h

ODMenu_OBJC_FILES = \
ODSliderItem.m \
ODCheckBoxItem.m \
ODSelectionGroup.m \
ODMenu.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

