include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = FMenu

FMenu_HEADER_FILES = \
FSliderItem.h \
FCheckBoxItem.h \
FMenu.h

FMenu_OBJC_FILES = \
FSliderItem.m \
FCheckBoxItem.m \
FMenu.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

