include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsFont

libNPEngineGraphicsFont_HEADER_FILES = \
NPFont.h \
NPFontManager.h

libNPEngineGraphicsFont_OBJC_FILES = \
NPFont.m \
NPFontManager.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

