include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsShader

libNPEngineGraphicsShader_OBJC_FILES = 

libNPEngineGraphicsShader_HEADER_FILES =

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

