include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCore

libNPEngineCore_SUBPROJECTS = \
	Basics \
	Math \
	NPObject \
	Log \
    File \
	Timer \
    Resource \
    RandomNumbers \
    Utilities \
    World

libNPEngineCore_OBJC_FILES = \
NPEngineCore.m

libNPEngineCore_HEADER_FILES = \
NPEngineCore.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

