include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineCore
LIBRARY_NAME=libNPEngineCore

SUBPROJECTS = \
	Basics \
	Math \
	NPObject \
	Log \
	Timer

libNPEngineCore_OBJC_FILES = \
NPEngineCore.m

libNPEngineCore_HEADER_FILES = \
NPEngineCore.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
