include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreMath

libNPEngineCoreMath_C_FILES = \
FVector.c \
FMatrix.c \
FQuaternion.c \
Matrix.c \
IBBox.c \
IVector.c \
IRectangle.c \
Quaternion.c \
Vector.c \
Plane.c \
FPlane.c \
Ray.c \
FRay.c \
FRectangle.c \
FVertex.c \
Pluecker.c \
FPluecker.c \
FTriangle.c \
NpMath.c

libNPEngineCoreMath_HEADER_FILES = \
Constants.h \
FMatrix.h \
FQuaternion.h \
FVector.h \
Matrix.h \
IBBox.h \
IVector.h \
IRectangle.h \
Quaternion.h \
Random.h \
Vector.h \
Plane.h \
FPlane.h \
Ray.h \
FRay.h \
FRectangle.h \
FVertex.h \
Pluecker.h \
FPluecker.h \
FTriangle.h \
NpMath.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

