include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineGraphicsModel
LIBRARY_NAME=libNPEngineGraphicsModel

libNPEngineGraphicsModel_OBJC_FILES = \
NPSUXModel.m \
NPSUXModelGroup.m \
NPSUXModelLod.m \
NPVertexBuffer.m \
NPModelManager.m

libNPEngineGraphicsModel_HEADER_FILES = \
NPSUXModel.h \
NPSUXModelGroup.h \
NPSUXModelLod.h \
NPVertexBuffer.h \
NPModelManager.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
