include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineGraphicsModel
LIBRARY_NAME=libNPEngineGraphicsModel

libNPEngineGraphicsModel_OBJC_FILES = \
NPSUXModel.m \
NPVertexBuffer.m

libNPEngineGraphicsModel_HEADER_FILES = \
NPSUXModel.h \
NPVertexBuffer.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
