include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreColor

libNPEngineCoreColor_C_FILES = \
ColorConversions.c \
Whitepoint.c \
NpColor.c

libNPEngineCoreColor_HEADER_FILES = \
ColorConversions.h \
Whitepoint.h \
NpColor.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

