include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreColor

libNPEngineCoreColor_C_FILES = \
NpColor.c

libNPEngineCoreColor_HEADER_FILES = \
NpColor.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

