include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreTimer

libNPEngineCoreTimer_OBJC_FILES = \
NPTimer.m

libNPEngineCoreTimer_HEADER_FILES = \
NPTimer.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

