include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsGeometry

libNPEngineGraphicsGeometry_HEADER_FILES = \
NPVertexArray.h

libNPEngineGraphicsGeometry_OBJC_FILES = \
NPVertexArray.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

