include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreNPObject

libNPEngineCoreNPObject_OBJC_FILES = \
NPObject.m \
NPObjectManager.m

libNPEngineCoreNPObject_HEADER_FILES = \
NPObject.h \
NPObjectManager.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

