include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphics

libNPEngineGraphics_SUBPROJECTS = \
    Image \
	Material \
    Font \
	Model \
	RenderContext \
    R2VB \
    RenderTarget \
    State \
    Viewport

libNPEngineGraphics_OBJC_FILES = \
NPEngineGraphics.m \
NPOrthographicRendering.m

libNPEngineGraphics_HEADER_FILES = \
NPEngineGraphics.h \
NPEngineGraphicsConstants.h \
NPOrthographicRendering.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make



