include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphics

libNPEngineGraphics_SUBPROJECTS = \
    Camera \
    Image \
	Material \
	Model \
	RenderContext \
    RenderTarget \
    State \
    Viewport

libNPEngineGraphics_OBJC_FILES = \
NPEngineGraphics.m

libNPEngineGraphics_HEADER_FILES = \
NPEngineGraphics.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make



