include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineGraphics
LIBRARY_NAME=libNPEngineGraphics

SUBPROJECTS = \
    Camera \
    Image \
	Material \
	Model \
	RenderContext

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/aggregate.make

