include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsUtilities

libNPEngineGraphicsUtilities_HEADER_FILES = \
NPPrimitivesRendering.h

libNPEngineGraphicsUtilities_OBJC_FILES = \
NPPrimitivesRendering.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

