include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreUtilities

libNPEngineCoreUtilities_OBJC_FILES = \
NSData+NPEngine.m \
NSError+NPEngine.m

libNPEngineCoreUtilities_HEADER_FILES = \
NSData+NPEngine.h \
NSError+NPEngine.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

