include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineCoreLog
LIBRARY_NAME=libNPEngineCoreLog

libNPEngineCoreLog_OBJC_FILES = \
NPLogger.m

libNPEngineCoreLog_HEADER_FILES = \
NPLogger.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
