include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineInput

libNPEngineInput_OBJC_FILES = \
NPEngineInput.m \
NPKeyboard.m \
NPMouse.m \
NPInputAction.m \
NPInputActions.m 

libNPEngineInput_HEADER_FILES = \
NPEngineInput.h \
NPKeyboard.h \
NPMouse.h \
NPInputAction.h \
NPInputActions.h 

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make



