include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineCoreNPObject
LIBRARY_NAME=libNPEngineCoreNPObject

libNPEngineCoreNPObject_OBJC_FILES = \
NPObject.m \
NPObjectManager.m

libNPEngineCoreNPObject_HEADER_FILES = \
NPObject.h \
NPObjectManager.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
