include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineGraphicsState
LIBRARY_NAME=libNPEngineGraphicsState

libNPEngineGraphicsState_HEADER_FILES = \
NPState.h \
NPAlphaTestState.h \
NPDepthTestState.h \
NPCullingState.h \
NPBlendingState.h \
NPStateConfiguration.h \
NPStateSet.h

libNPEngineGraphicsState_OBJC_FILES = \
NPState.m \
NPAlphaTestState.m \
NPDepthTestState.m \
NPCullingState.m \
NPBlendingState.m \
NPStateConfiguration.m \
NPStateSet.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
