include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreResource

libNPEngineCoreResource_OBJC_FILES = \
NPResource.m

libNPEngineCoreResource_HEADER_FILES = \
NPResource.h \
NPPResource.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

