include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineGraphicsImage
LIBRARY_NAME=libNPEngineGraphicsImage

libNPEngineGraphicsImage_HEADER_FILES = \
NPImage.h \
NPImageManager.h

libNPEngineGraphicsImage_OBJC_FILES = \
NPImage.m \
NPImageManager.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
