include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineCoreFile
LIBRARY_NAME=libNPEngineCoreFile

libNPEngineCoreFile_OBJC_FILES = \
NPPathManager.m

libNPEngineCoreFile_HEADER_FILES = \
NPPathManager.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
