include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineCoreFile
LIBRARY_NAME=libNPEngineCoreFile

libNPEngineCoreFile_OBJC_FILES = \
NPPathManager.m \
NPLocalPathManager.m \
NPRemotePathManager.m

libNPEngineCoreFile_HEADER_FILES = \
NPPathManager.h \
NPLocalPathManager.h \
NPRemotePathManager.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
