include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineCoreFile
LIBRARY_NAME=libNPEngineCoreFile

libNPEngineCoreFile_OBJC_FILES = \
NPFile.m \
NPPathManager.m \
NPLocalPathManager.m \
NPRemotePathManager.m \
NPURLDownload.m \
NPURLDownloadManager.m


libNPEngineCoreFile_HEADER_FILES = \
NPFile.h \
NPPathManager.h \
NPLocalPathManager.h \
NPRemotePathManager.h \
NPURLDownload.h \
NPURLDownloadManager.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
