include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsShader

libNPEngineGraphicsShader_OBJC_FILES = \
NPShader.m \
NPShaderConfiguration.m

libNPEngineGraphicsShader_HEADER_FILES = \
NPShader.h \
NPShaderConfiguration.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

