include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsShader

libNPEngineGraphicsShader_OBJC_FILES = \
NPShader.m \
NPEffect.m \
NPEffectTechnique.m \
NPEffectCompiler.m

libNPEngineGraphicsShader_HEADER_FILES = \
NPShader.h \
NPEffect.h \
NPEffectTechnique.h \
NPEffectCompiler.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

