include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsModel

libNPEngineGraphicsModel_HEADER_FILES = \
NPSUX2Model.h \
NPSUX2MaterialInstance.h \
NPSUX2ModelLOD.h \
NPSUX2VertexBuffer.h

libNPEngineGraphicsModel_OBJC_FILES = \
NPSUX2Model.m \
NPSUX2MaterialInstance.m \
NPSUX2ModelLOD.m \
NPSUX2VertexBuffer.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

