include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreNPObject

libNPEngineCoreNPObject_OBJC_FILES = \
NPObject.m \
NPObjectManager.m \
NSArray+NPPObject.m \
NSPointerArray+NPPObject.m

libNPEngineCoreNPObject_HEADER_FILES = \
NPPObject.h \
NPObject.h \
NPObjectManager.h \
NSArray+NPPObject.h \
NSPointerArray+NPPObject.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

