include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreFile

libNPEngineCoreFile_OBJC_FILES = \
NSFileManager+NPEngine.m \
NPFile.m \
NPLocalPathManager.m \
NPAssetArray.m

libNPEngineCoreFile_HEADER_FILES = \
NSFileManager+NPEngine.h \
NPPStream.h \
NPFile.h \
NPPPersistentObject.h \
NPLocalPathManager.h \
NPAssetArray.h \
NpFile.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

