include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreFile

libNPEngineCoreFile_OBJC_FILES = \
NPPathUtilities.m \
NPFile.m \
NPMemoryStream.m

libNPEngineCoreFile_HEADER_FILES = \
NPPathUtilities.h \
NPPStream.h \
NPFile.h \
NPMemoryStream.h \
NPPPersistentObject.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

