include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreFile

libNPEngineCoreFile_OBJC_FILES = \
NPPathUtilities.m \
NPFile.m

libNPEngineCoreFile_HEADER_FILES = \
NPPathUtilities.h \
NPFile.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

