include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsViewport

libNPEngineGraphicsViewport_HEADER_FILES = \
NPViewport.h \
NPViewportManager.h

libNPEngineGraphicsViewport_OBJC_FILES = \
NPViewport.m \
NPViewportManager.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

