include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreContainer

libNPEngineCoreContainer_OBJC_FILES = \
NSPointerArray+NPEngine.m \
NSArray+NPPObject.m \
NSArray+NPPPersistentObject.m \
NSPointerArray+NPPObject.m \
NSPointerArray+NPPPersistentObject.m \
NPAssetArray.m

libNPEngineCoreContainer_HEADER_FILES = \
NSPointerArray+NPEngine.h \
NSArray+NPPObject.h \
NSArray+NPPPersistentObject.h \
NSPointerArray+NPPObject.h \
NSPointerArray+NPPPersistentObject.h \
NPAssetArray.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

