include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreBasics

libNPEngineCoreBasics_C_FILES = \
NpBasics.c \
NpCrc32.c \
NpFreeList.c \
NpSuperFastHash.c \
NpHalf.c


libNPEngineCoreBasics_HEADER_FILES = \
NpBasics.h \
NpCrc32.h \
NpHashFunctions.h \
NpMemory.h \
NpFreeList.h \
NpTypes.h \
NpHalf.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make


