include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineLog

libNPEngineLog_OBJC_FILES = \
NPLogger.m

libNPEngineLog_HEADER_FILES = \
NPLogger.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

