include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=iWave

iWave_OBJC_FILES = \
    main.m

ADDITIONAL_TOOL_LIBS += -lNPEngine2 -lglfw

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/tool.make

