include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=FFTWTest

FFTWTest_OBJC_FILES = \
    main.m

ADDITIONAL_TOOL_LIBS += -lfftw3 -lfftw3f -lNPEngine2

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/tool.make

