include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineCoreBasics
LIBRARY_NAME=libNPEngineCoreBasics

libNPEngineCoreBasics_C_FILES = \
Crc32.c \
NpFreeList.c \
SuperFastHash.c

libNPEngineCoreBasics_HEADER_FILES = \
Crc32.h \
HashFunctions.h \
Memory.h \
NpFreeList.h \
Types.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
