include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineCoreBasics
LIBRARY_NAME=libNPEngineCoreBasics

libNPEngineCoreBasics_C_FILES = \
NpBasics.c \
NpCrc32.c \
NpFreeList.c \
NpSuperFastHash.c


libNPEngineCoreBasics_HEADER_FILES = \
NpBasics.h \
NpCrc32.h \
NpHashFunctions.h \
NpMemory.h \
NpFreeList.h \
NpTypes.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
