include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineLog

libNPEngineLog_OBJC_FILES = \
NPLog.m \
NPLogFile.m

libNPEngineLog_HEADER_FILES = \
NPLog.h \
NPLogFile.h \
NPPLogger.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

