include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=ODOcean

ODOcean_HEADER_FILES = \
ODGaussianRNG.h \
ODPFrequencySpectrumGeneration.h \
ODPhillipsSpectrum.h \
ODPhillipsSpectrumFloat.h \
ODAmplitude.h

ODOcean_C_FILES = \
ODGaussianRNG.c \
ODAmplitude.c

ODOcean_OBJC_FILES = \
ODPFrequencySpectrumGeneration.m \
ODPhillipsSpectrum.m \
ODPhillipsSpectrumFloat.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

