include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=ODOcean

ODOcean_HEADER_FILES = \
ODGaussianRNG.h \
ODPFrequencySpectrumGeneration.h \
ODPhillipsSpectrum.h \
ODPhillipsSpectrumFloat.h \
ODPhillipsSpectrumDouble.h

ODOcean_C_FILES = \
ODGaussianRNG.c

ODOcean_OBJC_FILES = \
ODPhillipsSpectrum.m \
ODPhillipsSpectrumFloat.m \
ODPhillipsSpectrumDouble.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

