include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsR2VB

libNPEngineGraphicsR2VB_HEADER_FILES = \
NPR2VBConfiguration.h \
NPR2VBManager.h

libNPEngineGraphicsR2VB_OBJC_FILES = \
NPR2VBConfiguration.m \
NPR2VBManager.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

