include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngine
LIBRARY_NAME=libNPEngine

SUBPROJECTS = \
    Core \
    Graphics

libNPEngine_OBJC_FILES = \
NP.m

libNPEngine_HEADER_FILES = \
NP.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install

