include $(GNUSTEP_MAKEFILES)/common.make

NATIVE_LIBRARY_NAME=libNPEngine

libNPEngine_SUBPROJECTS = \
    Application \
    Core \
    Graphics \
    Input \
    Sound

libNPEngine_OBJC_FILES = \
NP.m

libNPEngine_HEADER_FILES = \
NP.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/native-library.make
include $(TGDA_DIR)/GNUmakefile.library.install

