include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineCore
LIBRARY_NAME=libNPEngineCore

libNPEngineCore_HEADER_FILES = \
NPObject.h \
NPLogger.h

libNPEngineCore_OBJC_FILES = \
NPObject.m \
NPLogger.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
