include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=Math
LIBRARY_NAME=libMath

libMath_C_FILES = \
FVector.c \
FMatrix.c \
Matrix.c \
Quaternion.c \
Vector.c

libMath_HEADER_FILES = \
Constants.h \
FMatrix.h \
FQuaternion.h \
FVector.h \
Matrix.h \
Quaternion.h \
Random.h \
Vector.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
