include $(GNUSTEP_MAKEFILES)/common.make


PACKAGE_NAME=GormObjCHeaderParser
LIBRARY_NAME=libMath

libMath_C_FILES = \
Random.c

libMath_HEADER_FILES = \
Constants.h \
Matrix.h \
Random.h \
Vector.h

ADDITIONAL_INCLUDE_DIRS = -I..


-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/library.make

-include GNUmakefile.postamble 
