include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreLog

libNPEngineCoreLog_OBJC_FILES = \
NPLogger.m

libNPEngineCoreLog_HEADER_FILES = \
NPLogger.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

