include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreUtilities

libNPEngineCoreUtilities_OBJC_FILES = \
NPStringUtilities.m

libNPEngineCoreUtilities_HEADER_FILES = \
NPStringUtilities.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

