include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreUtilities

libNPEngineCoreUtilities_OBJC_FILES = \
NSString+NPEngine.m \
NPStringList.m

libNPEngineCoreUtilities_HEADER_FILES = \
NSString+NPEngine.h \
NPStringList.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

