include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=NPEngineCoreUtilities
LIBRARY_NAME=libNPEngineCoreUtilities

libNPEngineCoreUtilities_OBJC_FILES = \
NPStringUtilities.m

libNPEngineCoreUtilities_HEADER_FILES = \
NPStringUtilities.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/library.make
include $(TGDA_DIR)/GNUmakefile.library.install
