include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreUtilities

libNPEngineCoreUtilities_OBJC_FILES = \
NSError+NPEngine.m \
NSString+NPEngine.m \
NPStringList.m \
NPParser.m

libNPEngineCoreUtilities_HEADER_FILES = \
NSError+NPEngine.h \
NSString+NPEngine.h \
NPStringList.h \
NPParser.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

