include $(GNUSTEP_MAKEFILES)/common.make

NATIVE_LIBRARY_NAME=libNPEngine2

libNPEngine2_SUBPROJECTS = \
    Log \
    Core \
    Sound

libNPEngine2_OBJC_FILES = \
NP.m

libNPEngine2_HEADER_FILES = \
NP.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/native-library.make
include $(TGDA_DIR)/GNUmakefile.library.install

