include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsTexture

libNPEngineGraphicsTexture_OBJC_FILES = \
NPTexture2D.m \
NPTextureBindingState.m

libNPEngineGraphicsTexture_HEADER_FILES = \
NPTexture2D.h \
NPTextureBindingState.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

