include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsTexture

libNPEngineGraphicsTexture_C_FILES = \
NpTextureSamplerParameter.c

libNPEngineGraphicsTexture_OBJC_FILES = \
NPSamplerObject.m \
NPTexture2D.m \
NPTexture3D.m \
NPTextureBindingState.m \
NPTextureBuffer.m \
NPTextureSamplingState.m

libNPEngineGraphicsTexture_HEADER_FILES = \
NpTextureSamplerParameter.h \
NPSamplerObject.h \
NPTexture2D.h \
NPTexture3D.h \
NPTextureBuffer.h \
NPTextureBindingState.h \
NPTextureSamplingState.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

