include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreFile

libNPEngineCoreFile_OBJC_FILES = \
NPPathUtilities.m \
NPFile.m \
NPPathManager.m \
NPLocalPathManager.m \
NPRemotePathManager.m \
NPURLDownload.m \
NPURLDownloadManager.m


libNPEngineCoreFile_HEADER_FILES = \
NPFile.h \
NPPathManager.h \
NPLocalPathManager.h \
NPRemotePathManager.h \
NPURLDownload.h \
NPURLDownloadManager.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

