include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineCoreThread

libNPEngineCoreThread_OBJC_FILES = \
NPSemaphore.m

libNPEngineCoreThread_HEADER_FILES = \
NPSemaphore.h

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

