include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=libNPEngineGraphicsState

libNPEngineGraphicsState_HEADER_FILES = \
NPState.h \
NPAlphaTestState.h \
NPDepthTestState.h \
NPCullingState.h \
NPBlendingState.h \
NPPolygonFillState.h \
NPColorWriteState.h \
NPStateConfiguration.h \
NPStateSet.h

libNPEngineGraphicsState_OBJC_FILES = \
NPState.m \
NPAlphaTestState.m \
NPDepthTestState.m \
NPCullingState.m \
NPBlendingState.m \
NPPolygonFillState.m \
NPColorWriteState.m \
NPStateConfiguration.m \
NPStateSet.m

include $(TGDA_DIR)/GNUmakefile.flags
include $(GNUSTEP_MAKEFILES)/subproject.make

